baseurl: /jekyll_demo
gitalk:
  enable: true  # 是否开启 Gitalk 评论
  owner:  yangdm2015  # GitHub 用户名     
  repo:         #仓库名称
  ClientID: 3fdb5793244e6d9d1729
  ClientSecret: dd92eb8c0d9ef5c1e7aaf5d4c1200d8268e88c0b
  admin:   yangdm2015 # GitHub 用户名
  distractionFreeMode: true