baseurl: /jekyll_demo
gitalk:
  enable: true  # 是否开启 Gitalk 评论
  owner:  yangdm2015  # GitHub 用户名     
  repo:  comments       #仓库名称
  ClientID: 0a8a6858308aaf06c70b
  ClientSecret: e1b2ff94a87cf18ceb667cc90a57d0a090af6eae
  admin:   yangdm2015 # GitHub 用户名
  distractionFreeMode: true